(* Generated by: ocaml-crunch
   Creation date: Thu, 1 Jan 1970 00:00:00 GMT *)

module Internal = struct
  let d_d3b07384d113edec49eaa6238ad5ff00 = "foo\n"

  let file_chunks = function
    | "a.ext" | "/a.ext" -> Some [ d_d3b07384d113edec49eaa6238ad5ff00; ]
    | _ -> None

  let file_list = [ "a.ext"; ]
end

let file_list = Internal.file_list

let read name =
  match Internal.file_chunks name with
  | None -> None
  | Some c -> Some (String.concat "" c)

let hash = function
  | "a.ext" | "/a.ext" -> Some "d3b07384d113edec49eaa6238ad5ff00"
  | _ -> None

let size = function
  | "a.ext" | "/a.ext" -> Some 4
  | _ -> None
